### PR TITLE
Repair talisman

### LINKED ISSUE #878: [Request] Use of Talisman Repairing of items in the Bauble slot.
Would it be possible for the talisman of repair to repair items in the bauble slot, such the Talisman of Remedium from Thaumic Tinkerer, that only get repaired when outside of the baubles slot. Sorry if this is oddly worded. o/

### PR DESCRIPTION
**Pull request by Lilylicious**
Closes #878 and #885. 

#885 is suboptimally fixed, but it's a step in the right direction (prevents items going missing and reported duping, since it doesn't repair while it contains items). Optimally we'd repair it when those things would not occur, instead of not repairing at all.

### CODE REVIEW

**Comment by MaPePeR** [comment]
You changed indentation in a weird way.

`bInvStack.getItem() instanceof IChiselItem` is a very very specific fix... i don't know why it dupes items when it is repaired, though....

**Comment by Lilylicious** [comment]
I'll take a look at my settings later, didn't notice any indentation
weirdness.

I figured a very specific fix followed by a general fix was better than
waiting before a general fix. Was doing baubles anyway.

**Comment by williewillus** [comment]
These both crash at runtime when the respective mods are not present.

**Comment by Lilylicious** [comment]
.. Ah. Wait until I fix that before merge.

**Comment by williewillus** [comment]
Move the chisel check or bauble repair to a separate @Optional.Method method, and call that method only when Loader.isModLoaded("modname") passes.
You might not need @Optional.Method, but it's a good safeguard to have

**Comment by Lilylicious** [comment]
Will do, oversight on my part. Thank you for noticing.

**Comment by Lilylicious** [comment]
All fixed, tested without mods and it works fine.

**Pull request merged**
