### PR TITLE
Destruction Catalyst, Hyperkinetic Lens and Catalitic Lens Config Options

### PR DESCRIPTION
**Pull request by ViolentNinjaD**
This pull request allows you to configure the Destruction Catalyst, Hyperkinetic Lens and Catalitic Lens.

The only problem is that the "Item disabled for server admin." messagte on my config options is posted twice in the chat log. I couldn't find out how to fix it :disappointed: Hopefully someone else knows how to do this.

### CODE REVIEW

**Comment by MaPePeR** [comment]
probably need to check for `world.isRemote`

**Comment by ViolentNinjaD** [comment]
Ok, can't change it for about another 16 hours :disappointed: I'll see what I can do then

**Comment by MaPePeR** [comment]
No need for sad smileys :)

**Comment by ViolentNinjaD** [comment]
There we go, I fixed the double message. I'll look into making the diff cleaner now.

**Comment by sinkillerj** [comment]
This will be handled personally.

**Comment by MaPePeR** [comment]
Since all these items should extend `ItemPE` there could be a helper method, that uses the unlocalized name to determine if the item is disabled or not.

**Comment by sinkillerj** [comment]
@MaPePeR I had the same thought but sticking with the native Forge config system at some point it has to use a string as a variable name, something which I've had a bad experience with in the past with java. I'm open to your thoughts on it though.

**Pull request closed without merging**
