### PR TITLE
Master

### PR DESCRIPTION
**Pull request by artman41**
- Added a new EMCMapper to allow for easier Manual Mod Integration.

- Added some key items from IC2 to the Mapper.

- Moved the one AE2 item to the mapper.

- fixed a typo in the console output.

### CODE REVIEW

**Comment by artman41** [comment]
Hopefully this will allow for easier compatibility with mods and allow for integration with key mods that the current system doesn't support, such as IC2.

**Comment by artman41** [comment]
Just noticed, the IC2 api contains multiple class files that weren't being shown in the package explorer in eclipse. Those files however should be easily deleted but, if need be, I can delete them and resubmit the pull request

**Comment by artman41** [comment]
Noticed that the IC2 Api was packaged with obfuscated code, deleted that to just leave behind the java files which are needed.

**Comment by sinkillerj** [comment]
We do not manually define EMC values for mod items, nor do we plan to.

**Pull request closed without merging**
