### PR TITLE
Prevent Consume from Unlearn Slot (Dupe Fix)

### PR DESCRIPTION
**Pull request by Robotia**
A player on my server found a dupe glitch where consuming items from the unlearn slot allows them to produce free EMC.

I wasn't able to replicate this myself, the entities kept disappearing for me, but here is the video of him doing it on my server :https://www.youtube.com/watch?v=OYIhOrFaCLU&feature=youtu.be

### CODE REVIEW

**Comment by Robotia** [comment]
@sinkillerj ?

**Comment by MaPePeR** [comment]
Can you explain the fix and what causes the dupe?

**Comment by Robotia** [comment]
Basically, unlearned items can be shift-clicked from the unlearn slot into the consume slot. This prevents that by raising the inventory index to 27. Index 27 and above is the player's inventory.

**Comment by MaPePeR** [comment]
I kind of disagree with this kind of fix. Because allowing to shift click from the unlearn slot is not the reason the dupe exists.

**Comment by MaPePeR** [comment]
This was instead fixed with #1220

**Pull request closed without merging**
