### PR TITLE
Ability to register items with NBTs, default potion, tipped arrow and enchanted books/items implementation and capability to store custom EMC in separate files (for 1.13)

### PR DESCRIPTION
**Pull request by JPANv2**
As previously requested, here is a 1.13 implementation of the NBT-handling and separate Custom EMC storage. Testing for 1.13.2 was done with only ProjectE and vanilla Minecraft this time, but the similar code was working for all tested mods (including TConstruct, Refined Storage and RFTools) in Minecraft v1.12.2 (It was just very hard to find custom-NBT enabled mods in 1.13).

Total changes from the 1.12 version of the code were:
- NSSItemWithNBT disappeared, as NSSItem with an optional tag field covered all cases, and eliminated redundancy.
- Brewing Mapper now uses exclusively the Forge Reflection methods, so it shouldn't throw any exceptions outwards.
- Normal Forge 1.13 changes, such as no more Meta field in items, "$OreDict" => "$Tag".

While I tried to Implement some Unit tests for the Cleaning and Calculating aspects (the API addons), I found it impossible to run said tests on a conventional manner, as they require some manner of ItemStack to run, and ItemStack requires at least some initialization of Minecraft, which I could do.

### CODE REVIEW

**Comment by JPANv2** [comment]
On a sidenote, I spent 6 hours trying to build the project, but every time, it fails with "A problem was found with the configuration of task ':reobfShadowJar' \n> No value has been specified for property 'mappings'."
It works on the Dev environment on eclipse and through "gradlew start", but I can't run it in Minecraft Launcher with Forge. Any Ideas how I can fix this?

**Comment by pupnewfster** [comment]
Not sure if you still up for it but if you want to port it to the 1.14 branch I can take a look at working on getting it merged. If not just say so and at some point when I have the time I may look at trying to manually port it.

**Comment by pupnewfster** [comment]
I am leaving this open for now while I continue to work on my [branch](https://github.com/pupnewfster/ProjectE/tree/nbt_nss) which implements this but using a slightly different concept of handling things/most things in this PR got rewrote from scratch with this PR just being used as a rough reference of what types of things are needed.

**Comment by pupnewfster** [comment]
Closing this as the 1.14 branch now has decent support for handling NBT.

**Pull request closed without merging**
