### PR TITLE
[de_DE.lang] Correct two typos, minor improvements

### PR DESCRIPTION
**Pull request by ErrorCraftLP**

### CODE REVIEW

**Comment by MaPePeR** [comment]
I think there are some missing keys in the german localistation. It would be great if you could take care of them, too.

Thanks for helping!

```
pe.redpick.mode3, pe.command.main.usage, pe.gemdensity.whitelist, pe.morningstar.mode3, pe.transmutation.transmute, pe.darkpick.mode2, item.pe_klein_star_1.name, pe.redpick.mode1, itemGroup.ProjectE, item.pe_klein_star_2.name, pe.morningstar.mode1, pe.darkpick.mode1, pe.darkpick.mode3, pe.morningstar.mode2, pe.redpick.mode2, pe.darkpick.mode4, item.pe_klein_star_4.name, pe.redpick.mode4, pe.morningstar.mode4, item.pe_klein_star_3.name, item.pe_klein_star_5.name, pe.gemdensity.blacklist, item.pe_klein_star_6.name
```

**Comment by ErrorCraftLP** [comment]
Yes, I know about that, this keys are the same in English and in German. I could re-add them if you want.

**Comment by MaPePeR** [comment]
For my statistic that would be good - not sure if the quality of the localisation would be improved though ;)

Any other opinions on duplicating english localisations into the lang file?

**Comment by ErrorCraftLP** [comment]
Just a note: @sinkillerj removed the duplicated strings in [this commit](https://github.com/sinkillerj/ProjectE/commit/f46ec2123c69a011f1e15e47f3dc635a5ae6b09f).

**Comment by williewillus** [comment]
I vote for keeping the keys even though the values are the same, it's less confusing and you won't be wondering "Is the key missing a translation or just the same as English?" It also allows easier changing if it ever decides to change.

**Comment by ErrorCraftLP** [comment]
So should I re-add them now?

**Comment by MaPePeR** [comment]
I'm also for readding them.

**Comment by ErrorCraftLP** [comment]
I added the strings back.

**Comment by MaPePeR** [comment]
I think we could translate Tallshot/Wideshot/Longshot with "3x Übereinander", "3x Nebeneinander", "3x hintereinander". 
What do you think?

**Comment by ErrorCraftLP** [comment]
Yes, I can do that in ca. 3 hours :)

**Pull request merged**
