### PR TITLE
BIG update of french languages

### PR DESCRIPTION
**Pull request by didis54**
I completely took over the translations to zero, everything is now up-to-date
I also got a small pleasure on a translation ^^: p

### CODE REVIEW

**Comment by didis54** [comment]
I took so much time on this X)

**Comment by didis54** [comment]
I think every week, i will come to update the french language ^^

**Comment by MaPePeR** [comment]
Thanks!

**Comment by didis54** [comment]
To err is human, right? I have already proposed a small patch for some words I miss, but yes if you see sentences that can be better rephrase go there

**Pull request merged**
