### PR TITLE
run checkstyle with gradle

### PR DESCRIPTION
**Pull request by MaPePeR**
Generated report: [githack.com link that renders the html](https://gist.githack.com/MaPePeR/702a4b972a9020398535/raw/fcddb48696a43eaac06ff93afe0393bbdfa412f3/ProjectE-checkstype-report.html)

I think we should define a coding convention for this repo, because the style is not very consistent across the repository (mostly because i can't stop myself from putting the { on the same line ;)  - the files i created pretty much dominate the top of the list -.-)

So what coding style should we go with?
(If someone knows an interactive 'survey', where one gets asked all the questions about coding style possibilities - that would be great)

(To keep this PR clean i will not try to fix the errors until we decided on this)

### CODE REVIEW

**Comment by williewillus** [comment]
I vote for pure Google style (one line between all sections, no wildcard imports, 2 space indentation, NO tabs, same-line open braces (!!!!!) 

https://google-styleguide.googlecode.com/svn/trunk/javaguide.html

**Comment by MaPePeR** [comment]
Yea, i tried to adopt the google code style to what we currently have, which is tabs (i like tabs) and next line open braces (most of the time)

**Comment by sinkillerj** [comment]
My guidelines:
Tabs, not spaces.
Braces on next line.
Avoid one line comparisons using ? :.

**Comment by williewillus** [comment]
I love ternaries :(
But yes, google style with next line and tabs is fine with me

**Comment by Parker8283** [comment]
I'll adapt to any style that gets put forth. Not saying I'll LIKE it :P

What is "Special Imports?"

**Comment by MaPePeR** [comment]
[Documentation for CustomImportOrder](http://checkstyle.sourceforge.net/config_imports.html#CustomImportOrder)

**Comment by sinkillerj** [comment]
As far as import order you can do whatever you want, I really dont care there lol.

**Comment by williewillus** [comment]
Does this plugin run at build time?
If so how will it enforce coding style in the source?

**Comment by Parker8283** [comment]
Yes it runs at build time, and get a plugin for your IDE. It will import the rules sheet, and give you realtime checkstyle errors.

**Comment by MaPePeR** [comment]
You can set it to make the build fail. 
Sadly I did not yet find a IntelliJ plug-in, that can read that checkstyle configuration. But we probably want to remove parts of it anyway. (javadoc fit all public methods is utopic, isn't it?)

**Comment by MaPePeR** [comment]
@sinkillerj if you say: braces on next line this also means, that you want
```
}
else if ( ... ) 
{
```

instead of
```
} else if 
{
```
right?

**Comment by williewillus** [comment]
Yeah, that's the way I've been doing it and have seen I it done around the code base for else ifs

**Comment by Parker8283** [comment]
Checkstyle IDEA is what I use. Just import the xml file.

**Comment by MaPePeR** [comment]
Yea, i got it working after the update.

**Comment by sinkillerj** [comment]
Yep, thats the way.

**Comment by MaPePeR** [comment]
xkcd 1513 code quality
;)

**Comment by MaPePeR** [comment]
I gave up on this.

**Pull request closed without merging**
