### PR TITLE
Added en_UD.lang

### PR DESCRIPTION
**Pull request by The-Fireplace**

### CODE REVIEW

**Comment by sinkillerj** [comment]
In order to accept this PR I'm going to need some more info on why you find it to be useful. If this is just one of Minecrafts joke languages its not worth implementing and maintaining.

**Comment by The-Fireplace** [comment]
Yeah, it's just one of Minecraft's joke languages. I might make a gradle
plugin at some point to auto-maintain it.

**Comment by sinkillerj** [comment]
Should that happen I would be interested.

**Comment by The-Fireplace** [comment]
I'll make a new PR when I have a gradle plugin to auto-generate it.

**Pull request closed without merging**
