### PR TITLE
Made EMC system use doubles

### PR DESCRIPTION
**Pull request by karelmikie3**
as the title states I made the entire EMC system use doubles.

### CODE REVIEW

**Comment by LemADEC** [comment]
Did we check the performance impact of this change?

**Comment by karelmikie3** [comment]
We haven't noticed any impact on performance and we are using it on a private server with a private modpack with around 200 mods.

**Comment by LemADEC** [comment]
could we actually measure it with a profiler like Opis?

**Comment by MaPePeR** [comment]
I'm more worried about accuracy than speed. So if we decide to do decimal digits I would prefer to see rationals.

**Comment by Shalashalska** [comment]
Doubles have 15-17 digits of precision, so I really don't think that will be an issue. Or, you could just increase the value of everything by a factor of 100.

**Comment by LemADEC** [comment]
there's no need for 15 digits precision, doubles takes more space in memory and more time to compute. So, what's the motivation for this change?

**Comment by Shalashalska** [comment]
It means that items that have crafting recipes that split inputs (f.e. stone slabs, carpets, BC pipes) can have proper EMC values.

**Comment by MaPePeR** [comment]
```
> 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1
0.9999999999999999
```

**Comment by karelmikie3** [comment]
Sadly this pullrequest has been denied

**Pull request closed without merging**
