### PR TITLE
Attempt to fix issue #466

### PR DESCRIPTION
**Pull request by multiplemonomials**
I fixed the RM furnace texture alignment and patched the collector bug.  It seems like, for some reason, under certain conditions displayEmc is being set to a much higher value than getStoredEmc() returns.  I fixed the check so that the texture doesn't glitch out, but I couldn't find the underlying problem.

### CODE REVIEW

**Comment by Xee1** [comment]
Why this isn't merged?

**Comment by Xee1** [comment]
This fix #466

**Comment by williewillus** [comment]
I think we can merge this lol it's been sitting here long enough

**Comment by Xee1** [comment]
Finally, I hope

**Comment by multiplemonomials** [comment]
Yeah, I don't know what's going on.

**Comment by Xen1290** [comment]
I found the issue(maybe), sinkillerj isn't watching the repository, so, we need to mention @sinkillerj

**Comment by sinkillerj** [comment]
I am fully aware of this and all other pull requests, this pull comes with its own caveats and is still under evaluation.

**Comment by williewillus** [comment]
Happy 6 month - a week birthday, PR 482 :p
Maybe you'll get merged soon??

**Comment by Xen1290** [comment]
Finally! Thanks

**Pull request merged**
