### PR TITLE
Integrate GraphMapper

### PR DESCRIPTION
**Pull request by MaPePeR**
This is an extension of  PR #299  [(differences to other PR)](https://github.com/MaPePeR/ProjectE/compare/MaPePeR:graphMapper...integrateGraphMapper)

Contains:
* `NormalizedSimpleStack`: Identify Item by ItemID & Metadata. Keeps track of all Metadata values that are used to later add 'Object:Metadata -> Object:Metadata Wildcard' Conversions.
* `IEMCMapper<NormalizedSimpleStack>` used to add Conversions and Fixed Value mappings to the GraphMapper: Implemented for: Lazy Init, Lazy Init with OreDictionary, Crafting, Smelting, Fluids (TODO: Alloy Smelters, for example)
* `IRecipeMapper` Interface to Implement the `IRecipe` to `ItemStack`-Ingredients logic. Implemented for `ShapedRecipe`, `ShapelessRecipes`, `ShapedOreRecipe`, `ShapelessOreRecipe`. (TODO: AE2-Recipes?)
* A lot of unit Tests for the `GraphMapper`

So the Code in `EMCMapper` outputs the differences to the default EMCMapping and these only cointains the wrong EMC value for hardened clay. Whats left to do is, to remove the old mapping and replace it with this one.

### CODE REVIEW

**Comment by MaPePeR** [comment]
Sadly I will not have as much time to work on ProjectE in the future as I had in the last weeks, so I will not be able to and should not continue my efforts in the project. 
So don't expect any more big pull requests/changes from me in the future. If I do them I probably neglected my other duties and that  would not be a good thing.

**Comment by sinkillerj** [comment]
@MaPePeR It appears that alot of places in this pull use spaces instead of tabs, could you get that cleaned up?

**Comment by MaPePeR** [comment]
I will try to get that cleaned up before Monday.

**Comment by sinkillerj** [comment]
Cheers, once thats done if you feel its good to go leave a reply and ill merge it in.

**Comment by MaPePeR** [comment]
I formatted the code and changed the generated EMC Value Type to `Long`.

I did not have time to:
* implement an `IEMCMapper` for Config-File Mappings from User
* Delete the old Mapping Code
* Make the EMC System use the new Code

**Comment by MaPePeR** [comment]
I started testing this with the Madpack 2: The code that 'flattens' crafting-recipes with oredict-ingredients to 'flat' recipes want to allocate more than 3GB of memory...

**Comment by shobu9** [comment]
Can i have access :3?

**Comment by MaPePeR** [comment]
so with the latest commits this is the difference to the normal mapping when adding it to Madpack 2: https://gist.github.com/MaPePeR/5ca9e543c89ab7fe3f43

The leather armor is a problem because there is a 3Cloth->3Cloth Recipe the mapper can not handle at the moment.

Sandstone is a problem because another cycle-recipe that i have not yet figured out (but maybe its easier to just set a fixed value for these)

Not sure whats wrong with the BiblioIronLamp.

**Comment by MaPePeR** [comment]
With the latest commits it now maps all the values i want it to.

So now i only need to remove the old mapping code and fully replace it.

**Comment by sci4me** [comment]
This PR is needed so badly lol... can't wait for it!

**Comment by MaPePeR** [comment]
Its definitely not a solution to all the problems, but probably a step in the right direction. Its not finished though - but a lot closer than it was some days before

**Comment by MaPePeR** [comment]
I just tried this with IronChest, and it seems to pick up correct mappings.

**Comment by MaPePeR** [comment]
So i just removed the old mapping code... I think its finished now. There is still stuff to implement, but that are things for other pull requests:

* More IEMCMapper Implementations (Chisel, Alloy Smelters, and and and...)
* API Work
* Reviving IMC? (I disabled its effect for now)

For Reference, this is what the generated config file looks like at the moment:

```
# Configuration file

enabledmappers {
    # Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.CraftingManager [default: true]
    B:CraftingMapper=true

    # Uses the `custom_emc.cfg` File to add EMC values. [default: true]
    B:CustomEMCMapper=true

    # Adds Conversions for fluid container items and fluids. [default: true]
    B:FluidMapper=true

    # Default values for Items [default: true]
    B:LazyMapper=true

    # Default values for a lot of Mod - OreDictionary Names. [default: true]
    B:OreDictionaryMapper=true

    # Add Conversions for `FurnaceRecipes` [default: true]
    B:SmeltingMapper=true
}


mapperConfigurations {

    OreDictionaryMapper {
        # Set EMC=0 for everything that has an OD Name that starts with `ore`, `dust` or `crushed` besides `dustPlastic` [default: true]
        B:blacklistOresAndDusts=true
    }

    CraftingMapper {
        # If this option is enabled items that are made by crafting, with unconsumed ingredients, should only get an emc value, if the unconsumed item also has a value. (Examples: Extra Utilities Sigil, Cutting Board, Mixer, Juicer...) [default: true]
        B:emcDependencyForUnconsumedItems=true

        irecipeimplementations {
            # Maps `IRecipe` crafting recipes that extend `ShapedOreRecipe` or `ShapelessOreRecipe`. This includes CraftingRecipes that use OreDictionary ingredients. [default: true]
            B:enableVanillaOreRecipeMapper=true

            # Maps `IRecipe` crafting recipes that extend `ShapedRecipes` or `ShapelessRecipes` [default: true]
            B:enableVanillaRecipeMapper=true
        }

    }

    SmeltingMapper {
        # If X has a value and is smelted from Y, Y will get a value too. This is an experimental thing and might result in Mappings you did not expect/want to happen. [default: false]
        B:doBackwardsMapping=false
    }

}
```

Anything else i should change/add? 
@sinkillerj

**Comment by MaPePeR** [comment]
So i just rewrote the history and it now knows that the commits actually belong to my account. It still says, that the PR can be merged, so i guess i did it right?

For Reference the script i used:

```
#!/bin/sh
 
git filter-branch --env-filter '

OLD_EMAIL="mapeper@example.com"
CORRECT_NAME="MaPePeR"
CORRECT_EMAIL="MaPePeR@users.noreply.github.com"
if [[ $GIT_COMMIT == 97bcc53049b35c6422200ca6f022f4177918601f ]] \
	|| [[ $GIT_COMMIT == 7d321c82cc1a26d8205ddddae66e74e3c5bd61a4 ]] \
	|| [[ $GIT_COMMIT == 5a9165f7cdf839a48def12fb2c9c654204b0f3a0 ]] \
	|| [[ $GIT_COMMIT == 0b3c98b425f4ff375048c3179d307d2a0d7a6d3f ]] \
	|| [[ $GIT_COMMIT == ed4d93abbe83e1a38ad6a5ce40cfa432f5014f0f ]] \
	|| [[ $GIT_COMMIT == cfcab4c066aa40052011c297b7cfdc7a5603d09c ]] \
	|| [[ "$GIT_COMMITTER_NAME" != "MaPePeR" ]]
then
true
else
	if [[ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]]
	then
	    export GIT_COMMITTER_NAME="$CORRECT_NAME"
	    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
	fi
	if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
	then
	    export GIT_AUTHOR_NAME="$CORRECT_NAME"
	    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
	fi
fi

'  master..integrateGraphMapper
```

The hardcoded hashes are commits that are already merged.

And the usage of `master..integrateGraphMapper` should also make sure, that i only rewrite commits that are not yet in master

**Pull request merged**
