### PR TITLE
Lets other mods do flight

### LINKED ISSUE #975: [1.9 BETA] ProjectE conflicting with Morph flight.
Version: ProjectE-1.7.10-PE1.9.0B

 The current beta release of ProjectE is conflicting with Morph flight in some way. I tested ProjectE-1.7.10-PE1.8.0 to see if it also conflicted and flight works with no problems. I wish I could give more info, hope this helps. 

Thanks for this wonderful mod, keep it up!

### PR DESCRIPTION
**Pull request by Lilylicious**
Fixes #975

### CODE REVIEW

**Comment by williewillus** [comment]
Doesn't work, this needs to be per-player. The PlayerChecks object doesn't have any state of its own besides the collections of players so this needs to be something like a Map<Player, Boolean>

**Comment by Lilylicious** [comment]
Update incoming

**Comment by williewillus** [comment]
My name is ~~Donald Trump~~ williewillus and I approve of this ~~message~~ pull request

**Comment by mintcandle** [comment]
When would we see a version containing this fix?

**Comment by Lilylicious** [comment]
At the soonest a beta version will be out today (28th), but it could be tomorrow or a few days from now.

**Comment by DZCreeper** [comment]
@mintcandle If you want bug fixes as early as possible you can go to individual branches like https://github.com/Lilylicious/ProjectE/tree/fl and download the repository branch and run the build script yourself. I recommend against it because the delay between pull request and public release allows for testing and changes which are sometimes needed.

**Pull request merged**
