### PR TITLE
[DONE] Fix NEI Hotkeys in Transmutation GUI

### LINKED ISSUE #1057: can't show NEI-recipes/uses while having the transtable/transtablet open
when pressing 'R' on a item, it doesnt show the item, this only occurs while in the gui of the transmutationtable or the transmutationtablet

### PR DESCRIPTION
**Pull request by MaPePeR**
Fixes #1057

### CODE REVIEW

**Comment by MaPePeR** [comment]
Anything wrong with this PR? @sinkillerj

**Comment by sinkillerj** [comment]
This could cause issues with the filter box and IMO the issue is of non importance.

**Comment by MaPePeR** [comment]
I tested it and it worked. Did you test it and encounter any problems?

**Comment by MaPePeR** [comment]
Surely this is not a major game breaking bug, but it is an annoyance that we can fix it, so why shouldn't we? Especially, if we want to call it finished sometime. 

If you look at the changes of this PR, you can see, that if `this.textboxFilter.isFocussed() == true` the instructions that are run are 100% identical. 

If it is not true it just defaults to `super.keyTyped`, instead of checking for the escape and inventory key ourself.

**Comment by williewillus** [comment]
I guess this doens't really matter anymore since NEI is ded

**Pull request closed without merging**
