### PR TITLE
Split buy and sell EMC Values & Multiplier

### LINKED ISSUE #594: Tooltips: show durability EMC loss/stored EMC gain
Maybe the tooltips should show a bit more how the actual value is calculated.

Like: 

`BaseValue + StoredEMC + EnchantBonus- DurabilityLoss` ...

### LINKED ISSUE #988: Duping tools with enchantments
As a player has reported to me, duping tools with enchants doesn't work. It asks for the tools emc + enchant emc, but it only outputs normal tools. On a side note, and maybe related to this, the reported tools duped by this would not repair. The repair part could be my doing, but I'm leaving it here incase it's related.

### PR DESCRIPTION
**Pull request by MaPePeR**
# Don't merge this!
## Merge #1015 instead, which also contains #984

With this PR:
* Fixes #988 
* Split a lot of calls to `getEmcValue` and `doesHaveEmc` into `getEmcValueForDestruction`, `getEmcValueForCreation`, `hasEmcValueForDestruction` and `hasEmcValueForCreation`. 
* Implements: #985, #618 Option to add a multiplier that is applied when something is converted to EMC/destroyed.   
  With Side Effects:
  * Have to use the left side or the lock slot to learn an item when its EMC has been reduced to 0. Cannot use Shift-Click to learn
  * Mercurial Eye cannot transmute Stone anymore  (Or should i not apply the multiplier for that?)
* Detailed EMC tooltips when sneaking. Shows amount removed because of durability and amount added for Enchantments. Fixes #594 (Does NOT show the Multiplier EMC yet!)

Missing:
* Fuel upgrading does not use the new methods yet, because i don't know which to use.
* Fuels in general (Should these also be reduced by the multiplier?)
* Tooltips that show the reduced EMC Value - but when and how? **Suggestions?**
* Diving Rod
* API (More API methods? Which one should replace our current?)
* Left Side of the Transmutation Table (Which items should be allowed in there?)

### CODE REVIEW

**Comment by williewillus** [comment]
* Fuel upgrading - should use whichever value is used when taking out of the right side of the transmutation (the emc -> item value, so buy I guess)
* Fuels (I assume you mean when being consumed by power items) should yield the item -> emc value aka sell value on consumption
* Tooltips - not sure
* Divining Rod - Should show the item -> emc value (sell) since the items being divined will eventually be sold via condensing, GoED-ing (did you update GOED?), or transmutation sacrifice
* API - Add extra methods and either deprecate the old ones or write super clear doc clarifying which one it now delegates to
* Left side of transmutation - anything which has a value period (need sell to teach table, need buy to filter outputs)

**Comment by MaPePeR** [comment]
Also fixes #989: It now only uses the "damage calculation" for an item, when it cannot find an emc value for the `id:metadata` pair. So it tries `id:metadata` and when it finds a value uses it. If there is no value it tries `id:0` and applies the damage multiplier using `ItemStack.getItemDamage()/ItemStack.getMaxDamage()`. (These call methods in `Item` which are overwritten by Redstone Arsenal causing the problem. Before it always applied the damage modifier regardless of metadata.)

So the damage multiplier still works for Vanilla Tools - not sure about others.

I changed the GOED to use the "item -> emc" value for condensing and "emc -> item" value when creating an item. 

With this PR it should be easy to integrate the requested #784 "unlearnable Items". Not sure if the GOED should automatically consume these, though. And how to visualize this property in the ToolTip.

I just noticed that "buy and sell" are very bad words to describe this, because its unclear if the player or the table is the one who is buying/selling.

**Comment by williewillus** [comment]
Yeah, maybe it's better to refer to it as "Creation" and "Sacrifice" (maybe something more arcane sounding when I can think of a word) to refer to emc -> item and item -> emc, respectively

**Comment by MaPePeR** [comment]
Besides the tooltip needing proper localisation & the API i think this is actually done now... .... ...

**Comment by MaPePeR** [comment]
So what do you think: How should we do the tooltip?

> Create EMC: 123
> Destroy EMC: 456

When they differ and 

> EMC: 123

When both values are the same?

The problem is, that the "destroy" emc value is different for a lot of stuff: When you used a tool it looses emc, so the create/destroy values will not be the same anymore.

Another option would be to do (Maybe green/red colored?):

> EMC: 123/456

and if the values are the same

> EMC: 123

**Comment by williewillus** [comment]
I'd say keep them separate

**Comment by MaPePeR** [comment]
Then we need to agree on words.

**Comment by Carbon-Ghost** [comment]
pls be color blind friendly :o

**Comment by williewillus** [comment]
Creation and Destruction, or something similar or more lore-y.
I think a word like that make it pretty clear what process is happening (emc -> item and the reverse, respectively
Brain isn't working but maybe something like "Condensation" for creation since that's already in our lore, and make up anoter good word for item->emc. Dissolution maybe?

**Comment by MaPePeR** [comment]
That are very long words. I would prefer to keep these tooltips short. Maybe there is a symbol or single character we can use? 
Or just do a 

> C. EMC: 123
D. EMC: 456

And only write create/destroy/the long form  when sneaking?

**Comment by williewillus** [comment]
eh I feel like "to" and "from" are as ambiguous as buy and sell, I'd be down for C: and D:, with the full words on shift. Need the abbreviation to be localized separately from the main one though, just in case of weird languages

**Comment by MaPePeR** [comment]
So this is how it looks right now (Default config without the multiplier)

image

**Please** give your feedback.

**Comment by MaPePeR** [comment]
Closing this for #1015

**Pull request closed without merging**
