### PR TITLE
Update to Thaumcraft 5 API.

### PR DESCRIPTION
**Pull request by EXTER7**
Updates the Thaumcraft API. Fixes crash with Thaumcraft 5.

### CODE REVIEW

**Comment by MaPePeR** [comment]
With these changes it will not work with Thaumcraft 4 anymore, i guess?

**Comment by williewillus** [comment]
@MaPePeR TC5 is for Minecraft 1.8 so this PR is valid i think

**Comment by MaPePeR** [comment]
Ah, ok.

**Comment by sinkillerj** [comment]
Merging for now, but this feature will likely be moved to Thaumic Equivalence. @Lilylicious

**Pull request merged**
