### PR TITLE
Added null checks to items in DM Pedestal (and others).

### LINKED ISSUE #1604: random crashes with items in dm pedestal
[crash-2017-09-16_16.51.22-server.txt](https://github.com/sinkillerj/ProjectE/files/1308654/crash-2017-09-16_16.51.22-server.txt)

[17:00:11] [Server thread/INFO]: SpongeForge
    Minecraft: 1.11.2
    SpongeAPI: 6.1.0-SNAPSHOT-c4a7afd
    SpongeForge: 1.11.2-2393-6.1.0-BETA-2549
    Minecraft Forge: 13.20.1.2386

### PR DESCRIPTION
**Pull request by BenjaminUrquhart**
Should fix #1604 (log shows NullPointerException).

I also went ahead and added null checks to a few other random items. I'm not sure what items can go in the pedestal, so I didn't take any chances.

### CODE REVIEW

**Comment by williewillus** [comment]
Hi, thanks for the contribution!
I'd rather you change it to just return early if the tile is null, instead of adding null checks everywhere.

Also please make sure your whitespace is consistent with whatever is already there (tabs/spaces)

**Comment by williewillus** [comment]
Also, please make your pull request against the `mc1.12.x` branch, not `master`.

**Comment by BenjaminUrquhart** [comment]
I think I made the changes correctly, let me know if I messed something up ;)

**Comment by williewillus** [comment]
I think your commit history got muddled (since you made your PR branch off of master), could you try again with your PR branch made off of mc1.12.x? (feel free to recreate the PR or something if you need to)

**Comment by BenjaminUrquhart** [comment]
I'll remake the PR.

**Pull request closed without merging**
