### PR TITLE
Allowed the Iron Band to be created with a Volcanite Amulet

### PR DESCRIPTION
**Pull request by Parker8283**
I was surprised that this wasn't in here already :P

Also cleaned up the Evertide Amulet's implementation of IFluidContainerItem; one less opcode :P

EDIT: Reverted implementing IFluidContainerItem on the Volcanite Amulet. Forgot that Lava was 64 EMC.

### CODE REVIEW

**Comment by williewillus** [comment]
The way it is currently the Volcanite costs EMC to create lava.
We have to retain that - the way you have it I could just stick it in a Fluid Transposer and get free lava

**Comment by Parker8283** [comment]
Good point. Will fix momentarily.

**Comment by Parker8283** [comment]
And by fix I meant revert :P

**Comment by sinkillerj** [comment]
I wonder if there is a ore dict entry or something we could use to do this better.

**Comment by Parker8283** [comment]
I wish, but I don't believe so. I checked how EE2 did it, and this is what they did.

**Comment by MaPePeR** [comment]
Maybe we could do it similar to how gregtech damages tools when crafting and require the amulet to be charged somehow. 
That would complicate stuff, though.

**Comment by Parker8283** [comment]
This particular recipe in EE2 was just a standard shaped crafting recipe, and didn't require any extra EMC to craft this. But obviously, we could change that if we wanted, but as you said, would be complicating things.

**Pull request merged**
