### PR TITLE
[DONE but risky] Send search result instead search string in transmutation gui

### LINKED ISSUE #265: QED derps
cant take qed out of transmutation tablet,  and if shift clicked it comes out but emc is restored to tablet and QED goes missing dev 10 version

### PR DESCRIPTION
**Pull request by MaPePeR**
This should finally fix #265 and #474 and also allows to search for localized item names on servers.

Needs testing on a server...

How it works:
When both server & client call `TransmutationInventory.updateOutputs()` the Client will execute the method before the server and will send its ItemStacks in the output slots to the server. (This is caused by inventory clicks being evaluated on the client before the WindowClickPacket is send to the server)

When the client wants to update the outputs based on an Event that is not fired on the Server (keyPress, mouseClick into Searchbar) it uses `TransmutationInventory.updateOutputs(true)` which will result in a Packet that the server will write into its output slot without waiting for a call to `updateOutputs`.

This is needed, because otherwise the server would write the new output stacks into its internal slots before it recieves the slotClick-Event.

### CODE REVIEW

**Comment by sinkillerj** [comment]
This could use thorough testing, I may need to put out a alpha for this one. Regardless from a code standpoint it looks pretty solid.

**Comment by MaPePeR** [comment]
With this we could bring back the NEI enhanced filtering from #377, btw.

**Comment by sinkillerj** [comment]
I have no plans to ever bring back NEI search bar integration.

**Comment by MaPePeR** [comment]
Why not? It allows for better searching. And it only caused issues because the search happened server side as well. 

Also I need to sneak a check in there, that checks for the player knowledge. At the moment a bad client could fake knowledge, I think.

**Comment by MaPePeR** [comment]
#921 has this PR extended with the NEI Enhanced Searching. I would prefer to test both of these at once in an alpha version

**Comment by sinkillerj** [comment]
Do both need to be merged or just one? If just one close the dupe and resolve merge conflicts please.

**Pull request closed without merging**
