### PR TITLE
Chisel2 Mapper [finished?]

### PR DESCRIPTION
**Pull request by MaPePeR**
Sadly its hard to test this without Chisel being present, because ForgeGradle adds it magically.

bdews implementation: https://github.com/bdew/ProjectE/blob/f1b08624ff47c6cc716576701024cdb38ff3d297/src/main/java/moze_intel/projecte/emc/ChiselMapper.java

### CODE REVIEW

**Comment by MaPePeR** [comment]
Aaaaand it does not work if Chisel is not present, because to instantiate the class all the imports have to be successful. 

Anyone an idea how to solve this?

**Comment by williewillus** [comment]
Don't add a mapper to the mapper list unless their requisite mod is present?

**Comment by MaPePeR** [comment]
But i can't think of a way to determine the requisite mod for a mapper without loading the mapper

**Comment by artman41** [comment]
I have a fix.

do the following:

image

**Comment by MaPePeR** [comment]
I'm aware of this possibility, but it does not provide the flexibility i want.

**Comment by MaPePeR** [comment]
With the latest commits the mapper now does not crash anymore when Chisel is not present.

I don't see any issues with this anymore. Please test and report.

**Pull request merged**
